FROM python:3.10-slim


# RUN apt update && \
#     apt install --no-install-recommends -y build-essential software-properties-common && \
#     add-apt-repository -y ppa:deadsnakes/ppa && \
#     apt install --no-install-recommends -y python3.8 python3-pip python3-setuptools python3-distutils && \
#     apt clean && rm -rf /var/lib/apt/lists/*
    
# WORKDIR /usr/src/app



# RUN pip install setuptools==59.8.0 && pip install numpy==1.19.2
COPY requirements.txt ./
# RUN pip install tensorflow tensorflow-io
RUN pip install --no-cache-dir -r requirements.txt


COPY . .

EXPOSE 8000
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]